# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Budgetclaw < Formula
  desc "Local spend monitor for Claude Code"
  homepage "https://roninforge.org/budgetclaw"
  version "1.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RoninForge/budgetclaw/releases/download/v1.0.7/budgetclaw_1.0.7_darwin_amd64.tar.gz"
      sha256 "e47fcb82aca4f031578ff957d5d68766041cbc2536e5a92c852022f38fb4bc97"

      define_method(:install) do
        bin.install "budgetclaw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RoninForge/budgetclaw/releases/download/v1.0.7/budgetclaw_1.0.7_darwin_arm64.tar.gz"
      sha256 "a390f2fbc7d39b9a789aaa71d77a14825a267bb2ff0f8852d69577d077c77d07"

      define_method(:install) do
        bin.install "budgetclaw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RoninForge/budgetclaw/releases/download/v1.0.7/budgetclaw_1.0.7_linux_amd64.tar.gz"
      sha256 "4d4916f02e0be03f8a88d6d18efe151b07331e8385c61cc56acee6d122e2c18d"
      define_method(:install) do
        bin.install "budgetclaw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RoninForge/budgetclaw/releases/download/v1.0.7/budgetclaw_1.0.7_linux_arm64.tar.gz"
      sha256 "2e77784e92ef3f0fa304e1d8516096715a0cd7f68bec9678757a166a2721f0c3"
      define_method(:install) do
        bin.install "budgetclaw"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/budgetclaw version")
  end
end
