# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Budgetclaw < Formula
  desc "Local spend monitor for Claude Code"
  homepage "https://roninforge.org/budgetclaw"
  version "1.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RoninForge/budgetclaw/releases/download/v1.7.1/budgetclaw_1.7.1_darwin_amd64.tar.gz"
      sha256 "4668e243cde990bc380a5ff20de8bacf1aa62f761092f775fe1f8b242b1f6fcc"

      define_method(:install) do
        bin.install "budgetclaw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RoninForge/budgetclaw/releases/download/v1.7.1/budgetclaw_1.7.1_darwin_arm64.tar.gz"
      sha256 "52752d7498e13190ce3459f103f339780927985ed34287e9a4f6633d3463f795"

      define_method(:install) do
        bin.install "budgetclaw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RoninForge/budgetclaw/releases/download/v1.7.1/budgetclaw_1.7.1_linux_amd64.tar.gz"
      sha256 "34bac198cc3f7719376b851651e7c61d9f6c767d55c0d15a49acd8c1ef244d9b"
      define_method(:install) do
        bin.install "budgetclaw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RoninForge/budgetclaw/releases/download/v1.7.1/budgetclaw_1.7.1_linux_arm64.tar.gz"
      sha256 "510c84a92c56bb17308b44875e619f5a4f8f0c1f422c2d0eedd0622e43f83fd3"
      define_method(:install) do
        bin.install "budgetclaw"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/budgetclaw version")
  end
end
